# Generated by Django 3.2.6 on 2021-09-29 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=450)),
                ('lname', models.CharField(max_length=350)),
                ('profilepic', models.FileField(default='profile.png', upload_to='static/img/profile/pic/')),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(default='Welcome to CrimeHeist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
