# Generated by Django 3.2.6 on 2021-09-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
