# Generated by Django 3.2.6 on 2021-09-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210929_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.FileField(default='static/img/profile/pic/profile.png', upload_to='static/img/profile/pic/'),
        ),
    ]
