# Generated by Django 3.2.6 on 2021-09-29 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bird',
            field=models.CharField(default=datetime.datetime(2021, 9, 29, 14, 37, 50, 272181, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='fb',
            field=models.CharField(default=datetime.datetime(2021, 9, 29, 14, 37, 57, 928159, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gb',
            field=models.CharField(default=datetime.datetime(2021, 9, 29, 14, 38, 6, 688816, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gram',
            field=models.CharField(default=datetime.datetime(2021, 9, 29, 14, 38, 18, 826175, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linkin',
            field=models.CharField(default=datetime.datetime(2021, 9, 29, 14, 38, 27, 724791, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='origin',
            field=django_countries.fields.CountryField(default=datetime.datetime(2021, 9, 29, 14, 38, 36, 673636, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
    ]
