# Generated by Django 3.2.6 on 2021-09-30 16:20

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210929_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='origin',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
