# Generated by Django 3.2.6 on 2021-10-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entertain', '0004_alter_entertain_feature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertain',
            name='feature_image',
        ),
    ]
