# Generated by Django 3.2.6 on 2021-10-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_auto_20211004_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='feature_image',
        ),
    ]
